{
 "title": "SUDO Logs",
 "description": "Monitor SUDO Logs with Alloy and Loki",
 "tags": [
  "linux",
  "loki",
  "sudo",
  "secure"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   {
    "name": "label_name",
    "label": "Label Name",
    "query": {}
   },
   {
    "name": "label_value",
    "label": "Label Value",
    "query": {}
   },
   {
    "name": "job",
    "label": "Job",
    "query": {}
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Total Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Accepted SUDO Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=~\"$job\", hostname=~\"$instance\"} |= `sudo[` |~ `COMMAND=` != `command not allowed` [$__range])"
    }
   ]
  },
  {
   "title": "Total Rejected SUDO Events",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n  {job=~\"$job\", hostname=~\"$instance\"} |= \"sudo[\" |= \"command not allowed\"  [$__range]\r\n)\r\n"
    }
   ]
  },
  {
   "title": "SUDO Log Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"reject\\\":{.*|.+{\\\"accept\\\":{.*\" | __error__=\"\" [$__range])"
    }
   ]
  },
  {
   "title": "SUDO Log in bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(bytes_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} |=\"sudo[\" | pattern `<_> sudo[<_>]<_> <_>:<sudo_json_message>` | line_format\"{{ .sudo_json_message }}\" | json | sudo_json_message=~\".+{\\\"reject\\\":{.*|.+{\\\"accept\\\":{.*\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": {
    "content": "# SUDO JSON Log\n\nCreated by [VoidQuark](https://voidquark.com)\n\n- [Dashboard Source](https://github.com/voidquark/grafana-dashboards)\n\n- Follow me on [X](https://x.com/voidquark) for updates on new and current dashboards."
   }
  },
  {
   "title": "Accepted SUDO Events by User",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(submituser) (count_over_time({job=~\"$job\", hostname=\"$instance\"} \r\n|= \"sudo[\" \r\n|= \"COMMAND=\" != \"command not allowed\"\r\n| pattern `<_> sudo[<_>]: <submituser> : TTY=<tty> ; PWD=<pwd> ; USER=<target_user> ; COMMAND=<command>`\r\n| label_format submituser=\"{{.submituser}}\" \r\n| __error__=`` [$__auto]))",
     "legendFormat": "{{ submituser }}"
    }
   ]
  },
  {
   "title": "Rejected SUDO Events by User",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(submituser) (count_over_time({job=~\"$job\", hostname=\"$instance\"} |= `sudo` |= `command not allowed` | pattern `<time> <host> sudo[<pid>]: <submituser> : command not allowed ; TTY=<tty> ; PWD=<pwd> ; USER=<target_user> ; COMMAND=<runargv>` | label_format submituser=\"{{.submituser}}\" | __error__=`` [$__auto]))",
     "legendFormat": "{{submituser}}"
    }
   ]
  },
  {
   "title": "SUDO Recent Log",
   "type": "logs",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job\", hostname=~\"$instance\"} |= \"sudo[\" |= \"COMMAND=\" != \"command not allowed\"\r\n| pattern `<_> sudo[<_>]: <user> : TTY=<tty> ; PWD=<pwd> ; USER=<target_user> ; COMMAND=<command>`\r\n| line_format \"👤 {{ .user }} 📂 {{ .pwd }} 🎯 {{ .target_user }} 🖥️ {{ .command }}\""
    },
    {
     "direction": "backward",
     "expr": "{job=~\"$job\", hostname=~\"$instance\"} |= `sudo[` |~ `command not allowed` | regexp `(?P<user>\\w+) :(?P<reason>[^;]+).*USER=(?P<target_user>.+)*COMMAND=(?P<command>.+)$` | line_format `❌ {{.reason }} 👤 {{ .user }} 🎯 {{ .target_user }} 🖥️ {{ .command }}`"
    }
   ]
  },
  { "title": "Accepted SUDO Events - Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Accepted SUDO Events Details",
   "type": "table",
   "gridPos": { "h": 21, "w": 23, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job\", hostname=~\"$instance\"} \r\n|= \"sudo[\" \r\n|= \"COMMAND=\" != \"command not allowed\"\r\n| pattern `<_> sudo[<_>]: <user> : TTY=<tty> ; PWD=<pwd> ; USER=<target_user> ; COMMAND=<command>`\r\n##| line_format \"👤 {{ .user }} 📂 {{ .pwd }} 🎯 {{ .target_user }} 🖥️ {{ .command }}\""
    }
   ]
  },
  {
   "title": "Top 10 Accepted SUDO Events by User and Command",
   "type": "table",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 53 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (submituser,runargv ) (count_over_time({job=~\"$job\", hostname=~\"$instance\"} \r\n|= \"sudo[\" \r\n|= \"COMMAND=\" != \"command not allowed\"\r\n| pattern `<_> sudo[<_>]: <submituser> : TTY=<tty> ; PWD=<pwd> ; USER=<target_user> ; COMMAND=<runargv>`\r\n##| label_format submituser=\"{{.submituser}}\"\r\n| __error__=`` [$__auto])))",
     "legendFormat": "{{ submituser}} {{ runargv }}"
    }
   ]
  },
  { "title": "Rejected SUDO Events - Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Rejected SUDO Events Details",
   "type": "table",
   "gridPos": { "h": 21, "w": 23, "x": 0, "y": 66 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job\", hostname=~\"$instance\"} \r\n|= `sudo` \r\n|= `command not allowed`\r\n| pattern `<time> <host> sudo[<pid>]: <submituser> : <reason> ; TTY=<tty> ; PWD=<pwd> ; USER=<target_user> ; COMMAND=<runargv>` "
    }
   ]
  },
  {
   "title": "Top 10 Rejected SUDO Events by User and Command",
   "type": "table",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 87 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(10, sum by (sudo_reject_submituser, runargv) (count_over_time({job=~\"$job\", hostname=~\"$instance\"} \r\n|= `sudo` \r\n|= `command not allowed`\r\n| pattern `<time> <host> sudo[<pid>]: <submituser> : <reason> ; TTY=<tty> ; PWD=<pwd> ; USER=<target_user> ; COMMAND=<runargv>`  | __error__=\"\" [$__range])))",
     "legendFormat": "{{ sudo_reject_submituser }} {{ runargv }}"
    }
   ]
  }
 ]
}